pipeline{
    agent any
    
    stages{
        stage("maven"){
            steps{
                sh 'mvn clean'
                sh 'mvn install'
                sh 'mvn compile'
                sh 'mvn install'
                sh 'mvn test'
                sh 'mvn package'
            }
            
        }
    }
    
}