pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }

    stages{
        stage("maven"){
            steps{
                sh 'mvn clean validate compile install test package'
            }
            
        }

        stage('upload artifact'){
            steps{
                sh 'curl -u admin:AP6gCHaGvbw5kdFyGsCnMa2u4XR -T target/bio*.jar "http://54.163.33.1:8081/artifactory/geolocation/geo/bio_${BUILD_ID}"'
            }
        }
    }
    
}